//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Guardian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guardian()
        {
            this.Students = new HashSet<Student>();
        }

        public int GuardianID { get; set; }
        [Required(ErrorMessage = "First name is required")]
        [MaxLength(50)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        [MaxLength(50)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        [MaxLength(1)]
        [Display(Name = "Gender")]
        public string Gender { get; set; }
        [MaxLength(50)]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Cell contact")]
        [MaxLength(14)]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[(][0-9]{3}[)] [0-9]{3}-[0-9]{4}$", ErrorMessage = "Phone number should be of the format (XXX) XXX-XXXX")]
        public string CellContact { get; set; }
        [Display(Name = "Home contact")]
        [RegularExpression("^[(][0-9]{3}[)] [0-9]{3}-[0-9]{4}$", ErrorMessage = "Phone number should be of the format (XXX) XXX-XXXX")]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(14)]
        public string HomeContact { get; set; }

        public string SchoolID { get; set; }

        public virtual Guardian_Password Guardian_Password { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "Ward(s)")]
        public virtual ICollection<Student> Students { get; set; }
        [Display(Name = "Ward")]
        public List<int> StudentIDs { get; set; }
    }
}
