//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {

        public Mark(Student student, Subject subject, DateTime date, string username)
        {
            StudentID = student.StudentID;
            SubjectID = subject.SubjectID;
            Teacher_username = username;
            Grade = student.ClassGrade.Grade;
            Month = date.Month.ToString();
            Year = date.Year;
            Score = 0;

        }

        public Mark()
        {

        }

        public int StudentID { get; set; }
        public string SubjectID { get; set; }
        public string Teacher_username { get; set; }
        public string Grade { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public double Score { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
