//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MedicalInformation
    {

        public MedicalInformation()
        {

        }

        public MedicalInformation(int id)
        {
            StudentID = id;
            MedSummary = "Please add the student's medical information";
        }


        public int StudentID { get; set; }
        [MaxLength(255)]
        [Required(ErrorMessage = "Medical summary required")]
        [Display(Name = "Medical summary")]
        public string MedSummary { get; set; }

        
    
        public virtual Student Student { get; set; }
    }
}
