//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_Password
    {
      
        public Teacher_Password()
        {

        }

        public Teacher_Password(string username)
        {
            Username = username;
            Password = "5E884898DA28047151D0E56F8DC6292773603D0D6AABBDD62A11EF721D1542D8";

        }

        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
