//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Marks = new HashSet<Mark>();
            this.Students = new HashSet<Student>();
            this.ClassGrades = new HashSet<ClassGrade>();
            this.Subjects = new HashSet<Subject>();
        }

        [Required(ErrorMessage = "Username required")]
        [MaxLength(20)]
        [Display(Name = "Username")]
        public string Teacher_username { get; set; }
        [Display(Name = "School ID")]
        public string SchoolID { get; set; }
        [Required(ErrorMessage = "Role ID required")]
        [Display(Name = "Role ID")]
        public string RoleID { get; set; }
        [Required(ErrorMessage = "First name is required")]
        [MaxLength(50)]
        [Display(Name = "First name")]
        public string Firstname { get; set; }
        [MaxLength(50)]
        [Display(Name = "Middle name")]
        public string MiddleName { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        [MaxLength(50)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Gender is required")]
        [MaxLength(1)]
        [Display(Name = "Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Date of birth is required")]
        [Display(Name = "Date of birth")]
        public System.DateTime DOB { get; set; }
        [Display(Name = "Start date")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [MaxLength(50)]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Cell contact")]
        [MaxLength(14)]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[(][0-9]{3}[)] [0-9]{3}-[0-9]{4}$", ErrorMessage ="Phone number should be of the format (XXX) XXX-XXXX")]
        public string CellContact { get; set; }
        [Display(Name = "Home contact")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("^[(][0-9]{3}[)] [0-9]{3}-[0-9]{4}$", ErrorMessage = "Phone number should be of the format (XXX) XXX-XXXX")]
        [MaxLength(14)]
        public string HomeContact { get; set; }
        public string ClassID { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual Role Role { get; set; }
        public virtual School School { get; set; }
        public virtual Teacher_Password Teacher_Password { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassGrade> ClassGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
